In [119]:
import torch
import numpy as np

In [20]:
class Bebra():
    bebra_size = 21
    
    def __init__(self, depth, wide):
        self.depth = depth
        self.wide = wide

stas = Bebra(12,31)
stas.depth = 1425
stas.depth

1425

In [35]:
class Rectangle:

    def __init__(self, width, height):
        self.__width = width
        self.__height = height

    @property
    def width(self):
        return self.__width

    @width.setter
    def width(self, w):
        if w > 0:
            self.__width = w
        else:
            raise ValueError

    @property
    def height(self):
        return self.__height

    @height.setter
    def height(self, h):
        if h > 0:
            self.__height = h
        else:
            raise ValueError

    def area(self):
        return self.__width * self.__height

In [36]:
rect = Rectangle(43, 54)

In [37]:
rect.height = 3

In [38]:
rect.height

3

In [106]:
def F(name, *args, **kwds):
    print(name)
    print(args)
    print(kwds)
F(["5435, 6,767i"], [1,4,5,6],[4,6,6,68,9,])

['5435, 6,767i']
([1, 4, 5, 6], [4, 6, 6, 68, 9])
{}


In [55]:
dir(Rectangle)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'area',
 'height',
 'width']

In [56]:
class Vehicle(object):
    """docstring"""
    
    def __init__(self, color, doors, tires, vtype):
        """Constructor"""
        self.color = color
        self.doors = doors
        self.tires = tires
        self.vtype = vtype
    
    def brake(self):
        """
        Stop the car
        """
        return "%s braking" % self.vtype
    
    def drive(self):
        """
        Drive the car
        """
        return "I'm driving a %s %s!" % (self.color, self.vtype)


if __name__ == "__main__":
    car = Vehicle("blue", 5, 4, "car")
    print(car.brake())
    print(car.drive())

    truck = Vehicle("red", 3, 6, "truck")
    print(truck.drive())
    print(truck.brake())

car braking
I'm driving a blue car!
I'm driving a red truck!
truck braking


In [94]:
class zhiga(Vehicle):
    def __init__(self,  color, doors, tires, vtype, tonir="Black"):
        super().__init__(color, doors, tires, vtype)
        self._tonir = tonir
        
    def drive(self):
        print(super().drive())
        return "Tonirovka %s" % (self._tonir) + " no one Stop MEE"
v9 = zhiga("blue", 5, 4, "car", "white")

In [95]:
print(v9.drive())

I'm driving a blue car!
Tonirovka white no one Stop MEE


In [102]:
class A:
    def __init__(self):
        print('Initializing: class A')

    def sub_method(self, b):
        print('sub_method from class A:', b)


class B(A):
    def __init__(self):
        print('Initializing: class B')
        super().__init__()

    def sub_method(self, b):
        print('sub_method from class B:', b)
        super().sub_method(b + 1)

class X(B):
    def __init__(self):
        print('Initializing: class X')
        super().__init__()

    def sub_method(self, b):
        print('sub_method from class X:', b)
        super().sub_method(b + 1)


class Y(X):
    def __init__(self):
        print('Initializing: class Y')
        # super() с параметрами
        super(B, self).__init__()

    def sub_method(self, b):
        print('sub_method from class Y:', b)
        super().sub_method(b + 1)


x = X()
x.sub_method(1)
print('Обратите внимание как происходит инициализация')
print('классов при указании аргументов в функции super()')
y = Y()
y.sub_method(5)

Initializing: class X
Initializing: class B
Initializing: class A
sub_method from class X: 1
sub_method from class B: 2
sub_method from class A: 3
Обратите внимание как происходит инициализация
классов при указании аргументов в функции super()
Initializing: class Y
Initializing: class A
sub_method from class Y: 5
sub_method from class X: 6
sub_method from class B: 7
sub_method from class A: 8


In [131]:
x_data = [[1,1], [0,0], [0,1],[1,1]]
x_data = torch.tensor(x_data)
x_data.type(torch.float)

print((x_data/10000))
x_ones = torch.ones_like(x_data, dtype=torch.float)# retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

tensor([[1.0000e-04, 1.0000e-04],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0000e-04],
        [1.0000e-04, 1.0000e-04]])
Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 

Random Tensor: 
 tensor([[0.9584, 0.3743],
        [0.2218, 0.4555],
        [0.4759, 0.2861],
        [0.2183, 0.6273]]) 

